"""add_embedding_status

Revision ID: b37ae9f8159d
Revises: 9d88b1e0a817
Create Date: 2026-08-24 13:12:57.849424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b37ae9f8159d'
down_revision: Union[str, None] = '9d88b1e0a817'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_embeddings', sa.Column('status', sa.Enum('PENDING', 'EMBEDDED', 'FAILED', name='embeddingstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_embeddings', 'status')
    # ### end Alembic commands ###
